wrong config for script to see behaviour

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -3,9 +3,9 @@
 name: deployemnt for terraform code on AWS
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - feature/ci-cd
+  # push:
+  #   branches:
+  #     - feature/ci-cd
   pull_request:
     types:
       - opened
@@ -33,14 +33,12 @@ jobs:
           terraform fmt -check 
           terraform validate 
           echo "passed= $?" >> $GITHUB_OUTPUT
-
       - name: debug
         env:
           CHECK_ITEM: ${{ steps.tests.outputs.passed }}
           ALL_STEPS: ${{ toJson(steps) }}
         run: |
           ls ./.github/workflows/
-          echo " ${CHECK_ITEM}"
   check_quality_gate:
     permissions:
      statuses: write  
@@ -49,14 +47,14 @@ jobs:
     uses: ./.github/workflows/script-reuse.yaml
     with:
       Result: ${{ needs.deployment.outputs.step_output }}
-  # debug-job:
-  #   runs-on: ubuntu-latest
-  #   needs: deployment
-  #   steps:
-  #     - name: Debugging
-  #       run: |
-  #         echo "Debugging the deployment job"
-  #         echo "Passed: ${{ needs.deployment.outputs.step_output }}"
+  debug-job:
+    runs-on: ubuntu-latest
+    needs: deployment
+    steps:
+      - name: Debugging
+        run: |
+          echo "Debugging the deployment job"
+          echo "Passed: ${{ needs.deployment.outputs.step_output }}"
       # - name: checking for quality gate
       #   uses: actions/github-script@v6
       #   if: 
@@ -80,5 +78,12 @@ jobs:
       #   run: terraform destroy -auto-approve -var="aws_access_key=${AWS_ACCESS_KEY_ID}" -var="aws_secret_key=${AWS_SECRET_ACCESS_KEY}"
       
       
-
+          # if [[ $? -ne 0 ]]; then
+          #   echo "Terraform validation or formatting failed"
+          #   echo "passed=false" >> $GITHUB_OUTPUT
+          #   exit 1
+          # else
+          #   echo "Terraform validation and formatting passed"
+          #   echo "passed=true" >> $GITHUB_OUTPUT
+          # fi
         
